name: hello_world
author: valory
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiapubcoersqnsnh3acia5hd7otzt7kjxekr6gkbrlumv6tkajl6jm
fingerprint_ignore_patterns: []
agent: valory/hello_world:0.1.0:bafybeiess6jyy2bxxvqgprosift3yi5ifnwgccmnvfkmfftcps2eavjgue
number_of_agents: 4
---
benchmark_persistence_params:
  args: &id001
    log_dir: /benchmarks
public_id: valory/hello_world_abci:0.1.0
type: skill
models:
  0:
  - benchmark_tool:
      args: *id001
  1:
  - benchmark_tool:
      args: *id001
  2:
  - benchmark_tool:
      args: *id001
  3:
  - benchmark_tool:
      args: *id001
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_HELLO_WORLD_RPC:str:http://host.docker.internal:8545}
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559
