name: hello_world
author: valory
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiapubcoersqnsnh3acia5hd7otzt7kjxekr6gkbrlumv6tkajl6jm
fingerprint_ignore_patterns: []
agent: valory/hello_world:0.1.0:bafybeic5gs6qausrb3xgam4ighqvir7kf2q3wyzw2m5r4xlitzs5mdbcqi
number_of_agents: 4
deployment: {}
---
extra:
  benchmark_persistence_params:
    args: &id002
      log_dir: ${LOG_DIR:str:/benchmarks}
  params_args:
    args:
      setup: &id001
        all_participants: ${ALL_PARTICIPANTS:list:["0x0000000000000000000000000000000000000000"]}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
        consensus_threshold: ${CONSENSUS_THRESHOLD:int:null}
public_id: valory/hello_world_abci:0.1.0
type: skill
0:
  models:
    params:
      args:
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        setup: *id001
        hello_world_message: ${HELLO_WORLD_STRING_0:str:HELLO_WORLD! (from Agent 0)}
    benchmark_tool:
      args: *id002
1:
  models:
    params:
      args:
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        setup: *id001
        hello_world_message: ${HELLO_WORLD_STRING_1:str:HELLO_WORLD! (from Agent 1)}
    benchmark_tool:
      args: *id002
2:
  models:
    params:
      args:
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        setup: *id001
        hello_world_message: ${HELLO_WORLD_STRING_2:str:HELLO_WORLD! (from Agent 2)}
    benchmark_tool:
      args: *id002
3:
  models:
    params:
      args:
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        setup: *id001
        hello_world_message: ${HELLO_WORLD_STRING_3:str:HELLO_WORLD! (from Agent 3)}
    benchmark_tool:
      args: *id002
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${LEDGER_RPC:str:http://localhost:8545}
      chain_id: ${CHAIN_ID:int:31337}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
