[tool.poetry]
name = "open-autonomy"
version = "0.21.6"
description = "Open Autonomy Framework"
authors = ["developer-valory <develope@valory.xyz>"]
license = "Apache-2.0 license"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = ">=3.8.5,<4.0.0"
docker = "==7.1.0"
Flask = "==2.0.2"
open-aea = { version = "==2.0.7", extras = ["all"] }
open-aea-ledger-ethereum = "==2.0.7"
open-aea-ledger-ethereum-hwi = "==2.0.7"
open-aea-cli-ipfs = "==2.0.7"
ipfshttpclient = "==0.8.0a2"
multiaddr = "==0.0.9"
Werkzeug = "==2.0.3"
watchdog = ">=2.1.6"
pytest = "==7.4.4"
click = ">=8.1.0,<9"
tomte = { extras = ["tox", "docs"], version = "==0.4.0" }
mkdocs-monorepo-plugin = "^1.0.5"

[tool.poetry.group.dev.dependencies]
aiohttp = ">=3.8.5,<4.0.0"
asn1crypto = ">=1.4.0,<1.5.0"
ecdsa = ">=0.15"
web3 = "<8,>=7.0.0"
certifi = "*"
multidict = "*"
eth_typing = "*"
eth-account = ">=0.13.0,<0.14.0"
typing_extensions = ">=3.10.0.2,<=4.13.2"
hexbytes = "*"
packaging = "*"
pytest-asyncio = "*"
open-aea-ledger-cosmos = "==2.0.7"
open-aea-cosmpy = "==0.6.7"
grpcio = "==1.53.0"
hypothesis = "==6.21.6"
protobuf = ">=4.21.6,<4.25.0"
pytz = "==2022.2.1"
py-ecc = "==8.0.0"
python-dotenv = ">=0.14.5,<0.22.0"
requests = ">=2.28.1,<2.32.5"
texttable = "==1.6.7"
toml = "==0.10.2"
eth-utils = "==5.3.0"
eth-abi = "==5.2.0"
pycryptodome = "==3.20.0"
jsonschema = ">=4.3.0,<4.4.0"
gql = "==3.5.0"

[build-system]
requires = ["setuptools", "wheel", "poetry-core>=1.0.0"]
build-backend = "setuptools.build_meta"
