name: apy_estimation_hardhat
author: valory
version: 0.1.0
description: A set of agent reaching APY estimates
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeibqyfur7wusrbfga66hcbauxvhs2g3j5yhknsxlvyh6mil57aajyu
fingerprint_ignore_patterns: []
agent: valory/apy_estimation:0.1.0:bafybeigtwnns3lq4oiytr4xe36m3zhf3so6lvb22c2qx2qsspb7vcahgdy
number_of_agents: 4
---
public_id: valory/apy_estimation_abci:0.1.0
type: skill
models:
  params:
    args:
      consensus:
        max_participants: 4
      round_timeout_seconds: 1000.0
      observation_interval: 86400
      max_healthcheck: 43200
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      estimation:
        steps_forward: 1
      history_end: null
      history_interval_in_unix: 86400
      history_start: 1652544875
      optimizer:
        n_trials: 10
        timeout: 60
        n_jobs: 1
        show_progress_bar: false
        scoring: pinball
        alpha: 0.25
      pair_ids:
        uniswap_subgraph:
        - '0xae461ca67b15dc8dc81ce7615e0320da1a9ab8d5'
        spooky_subgraph:
        - '0x2a651563c9d3af67ae0388a5c8f89b867038089e'
        - '0x2b4c76d0dc16be1c31d4c1dc53bf9b45987fc75c'
      sleep_time: 10
      ipfs_domain_name: /dns/registry.autonolas.tech/tcp/443/https
---
public_id: valory/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: http://host.docker.internal:8545
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559
