name: Service
author: valory
version: 0.1.0
description: Description
aea_version: ">=1.0.0, <2.0.0"
license: Apache-2.0
agent: agent
network: hardhat
number_of_agents: 4
deployment: {}
dependencies: {}