agent_name: price_estimation_deployable
author: valory
version: 0.1.0
license: Apache-2.0
description: Price estimation agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0
- valory/http_client:0.1.0
- valory/ledger:0.1.0
contracts:
- valory/gnosis_safe:0.1.0
- valory/gnosis_safe_proxy_factory:0.1.0
- valory/offchain_aggregator:0.1.0
protocols:
- open_aea/signing:1.0.0
- valory/abci:0.1.0
- valory/contract_api:1.0.0
- valory/http:1.0.0
- valory/ledger_api:1.0.0
skills:
- valory/abstract_abci:0.1.0
- valory/abstract_round_abci:0.1.0
- valory/oracle_deployment_abci:0.1.0
- valory/price_estimation_abci:0.1.0
- valory/registration_abci:0.1.0
- valory/safe_deployment_abci:0.1.0
- valory/transaction_settlement_abci:0.1.0
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - console
      propagate: false
dependencies:
  open-aea-ledger-ethereum: {}
skill_exception_policy: just_log
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/price_estimation_abci:0.1.0
  host: ${ABCI_HOST:str}
  port: ${ABCI_PORT:int:26658}
  use_tendermint: ${ABCI_USE_TENDERMINT:bool:false}
---
public_id: valory/price_estimation_abci:0.1.0
type: skill
models:
  price_api:
    args:
      url: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PRICE_API_ARGS_URL:str}
      api_id: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PRICE_API_ARGS_API_ID:str}
      parameters: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PRICE_API_ARGS_PARAMETERS:list:none}
      response_key: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PRICE_API_ARGS_RESPONSE_KEY:str}
      headers: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PRICE_API_ARGS_HEADERS:none}
  randomness_api:
    args:
      url: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_RANDOMNESS_API_ARGS_URL:str}
      api_id: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_RANDOMNESS_API_ARGS_API_ID:str}
  params:
    args:
      consensus:
        max_participants: ${MAX_PARTICIPANTS:int}
      period_setup:
        safe_contract_address: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PARAMS_ARGS_PERIOD_SETUP_SAFE_CONTRACT_ADDRESS:str:none}
        oracle_contract_address: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PARAMS_ARGS_PERIOD_SETUP_ORACLE_CONTRACT_ADDRESS:str:none}
      round_timeout_seconds: ${PRICE_ESTIMATION_PARAMS_ROUND_TIMEOUT_SECONDS:float:7.0}
      tendermint_url: ${TENDERMINT_URL:str}
      tendermint_com_url: ${TENDERMINT_COM_URL:str}
      reset_tendermint_after: ${PRICE_ESTIMATION_PARAMS_RESET_TENDERMINT_AFTER:int:3}
      observation_interval: ${PRICE_ESTIMATION_PARAMS_OBSERVATION_INTERVAL:int:300}
      max_healthcheck: ${SKILL_PRICE_ESTIMATION_ABCI_MODELS_PARAMS_ARGS_MAX_HEALTHCHECK:int:1200}
---
public_id: valory/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${LEDGER_ADDRESS:str:http://hardhat:8545}
      chain_id: ${LEDGER_CHAIN_ID:int:31337}
