agent_name: oracle_deployable
author: valory
version: 0.1.0
license: Apache-2.0
description: Oracle agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0:QmcSFCqBgsz1MZYheyGJz53TDm8iLGeeqRRnupaazDDBmC
- valory/http_client:0.1.0:QmXXtNRaMrZqEdmT9LVDhcxSy7PNgvJdCXaQ5L9ZxM5cGm
- valory/ledger:0.1.0:QmbjPsymto6fKHZvFUTyMBnZeA7ZWoqfy3KXXJ7cVWkiE3
- valory/p2p_libp2p_client:0.1.0:QmZWFVzuMLAcLeVVimaHTGfj16ELAM2pdSLWtZTxqkvDZ4
contracts:
- valory/gnosis_safe:0.1.0:QmRNdXGRRQBMFXh5ZvtJeYvHt7559kV5r5EYU5JNUdRBKJ
- valory/gnosis_safe_proxy_factory:0.1.0:QmVkZtrgZ2ievXAonq9z33qbrxHi8piVGptuCGaGJYS1iM
- valory/offchain_aggregator:0.1.0:Qmaftfci6asBewVH3vKGtMJVcAdG71Vm6Qv493uRkT7b2h
- valory/service_registry:0.1.0:Qmf8AdK3VPVECCx4biHMGdVoFHkscY3H9sv9b4wyE9vmED
protocols:
- open_aea/signing:1.0.0:QmaGYpYEQjgbM37pBMiR7RcpeSLpztZyzDt2RF7sTXoMyU
- valory/abci:0.1.0:QmPh452wHDWf6xTnAENyXQED5UZNkU5dum98ZGfN9vZGhk
- valory/acn:1.1.0:QmZyXSCZoqiHsKqB8WFcUi1WcbMofk2SUgv4uzAhjAenuw
- valory/contract_api:1.0.0:QmX2mRDNNWUTwU6ivKD65R3bnfC9jkGuKCaWqzxoQdm7ni
- valory/http:1.0.0:QmbTD9GZg9MKBiQR3Tef1hS5YnGufUNSzrKpW8Eqgd6FUQ
- valory/ledger_api:1.0.0:QmcjydJiMqhEmSGJqnLKDjmGSXmV5KZhMvY6zGgHKUgFL4
- valory/tendermint:0.1.0:QmTebra2gtfrwfcxJj2vpoRrAawi6gvHSBtRjqfHxZ6YJV
skills:
- valory/abstract_abci:0.1.0:QmdfVoBSbRjea8XEgVym7ssSTj22kHcEhguNwyT4p4NtNe
- valory/abstract_round_abci:0.1.0:QmTGSxvHgFT9LHVGigsPhPC3fVnXv6dt9kAVUn11A3jNck
- valory/oracle_abci:0.1.0:QmYSzqCN69r2NPPwvmemxKk84sgx5BFS9WEM3KNg6UEcC9
- valory/oracle_deployment_abci:0.1.0:QmZqoXpQoiy8tKvsHo7pNPiDJwgVkPEQZQzeacRYeKWZqd
- valory/price_estimation_abci:0.1.0:QmTDi3XZU1uhNHKgp9aMuctQyfRh4uGbmQTeqzKCmhKkZP
- valory/registration_abci:0.1.0:QmeMt2MEhFNTUGmCd31KF5bXzd69fXaZXbp2fMTZGQiFaP
- valory/reset_pause_abci:0.1.0:Qmf14xmAgGWyTsLxYSHNoQTJmfP4Bf7qk4Qw8FY7QYUkP6
- valory/safe_deployment_abci:0.1.0:QmZwmh8qyjoWLgSPgRUuJcuzNDtn6xFXD49gwTePYNehZt
- valory/transaction_settlement_abci:0.1.0:QmWzRXddrmgZzuq8VQWV3XCdVsry2MjUyyvSDgugSxEBdD
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:/logs/logs.log}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/oracle_abci:0.1.0
  host: ${ABCI_HOST:str}
  port: ${ABCI_PORT:int:26658}
  use_tendermint: ${ABCI_USE_TENDERMINT:bool:false}
---
public_id: valory/oracle_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${SKILL_ORACLE_ABCI_MODELS_BENCHMARK_TOOL_ARGS_LOG_DIR:str:/benchmarks}
  price_api:
    args:
      url: ${SKILL_ORACLE_ABCI_MODELS_PRICE_API_ARGS_URL:str}
      api_id: ${SKILL_ORACLE_ABCI_MODELS_PRICE_API_ARGS_API_ID:str}
      parameters: ${SKILL_ORACLE_ABCI_MODELS_PRICE_API_ARGS_PARAMETERS:list:none}
      response_key: ${SKILL_ORACLE_ABCI_MODELS_PRICE_API_ARGS_RESPONSE_KEY:str}
      headers: ${SKILL_ORACLE_ABCI_MODELS_PRICE_API_ARGS_HEADERS:none}
  randomness_api:
    args:
      url: ${SKILL_ORACLE_ABCI_MODELS_RANDOMNESS_API_ARGS_URL:str}
      api_id: ${SKILL_ORACLE_ABCI_MODELS_RANDOMNESS_API_ARGS_API_ID:str}
  params:
    args:
      consensus:
        max_participants: ${MAX_PARTICIPANTS:int}
      period_setup:
        safe_contract_address: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_PERIOD_SETUP_SAFE_CONTRACT_ADDRESS:str:none}
        oracle_contract_address: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_PERIOD_SETUP_ORACLE_CONTRACT_ADDRESS:str:none}
      round_timeout_seconds: ${ORACLE_PARAMS_ROUND_TIMEOUT_SECONDS:float:7.0}
      tendermint_url: ${TENDERMINT_URL:str}
      tendermint_com_url: ${TENDERMINT_COM_URL:str}
      reset_tendermint_after: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_RESET_TENDERMINT_AFTER:int:10}
      observation_interval: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_OBSERVATION_INTERVAL:int:300}
      max_healthcheck: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_MAX_HEALTHCHECK:int:1200}
      broadcast_to_server: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_BROADCAST_TO_SERVER:bool:true}
      service_registry_address: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_SERVICE_REGISTRY_ADDRESS:str:none}
      on_chain_service_id: ${SKILL_ORACLE_ABCI_MODELS_PARAMS_ARGS_ON_CHAIN_SERVICE_ID:int:none}
  server_api:
    args:
      url: ${SKILL_ORACLE_ABCI_MODELS_SERVER_API_ARGS_URL:str}
---
public_id: valory/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${LEDGER_ADDRESS:str:https://staging.chain.autonolas.tech}
      chain_id: ${LEDGER_CHAIN_ID:int:31337}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: staging.acn.autonolas.tech:9006
    public_key: 02fc5fe35c21a1f8ba2de52fd38ef95379be19d5390f1275b825c343167590d3b7
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2022-01-01'
  not_before: '2021-01-01'
  public_key: 02fc5fe35c21a1f8ba2de52fd38ef95379be19d5390f1275b825c343167590d3b7
  save_path: .certs/acn_cosmos_9006.txt
