agent_name: oracle
author: valory
version: 0.1.0
license: Apache-2.0
description: Oracle agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- valory/abci:0.1.0
- valory/http_client:0.1.0
- valory/ledger:0.1.0
- valory/p2p_libp2p_client:0.1.0
contracts:
- valory/gnosis_safe:0.1.0
- valory/gnosis_safe_proxy_factory:0.1.0
- valory/offchain_aggregator:0.1.0
- valory/service_registry:0.1.0
protocols:
- open_aea/signing:1.0.0
- valory/abci:0.1.0
- valory/acn:1.1.0
- valory/contract_api:1.0.0
- valory/http:1.0.0
- valory/ledger_api:1.0.0
- valory/tendermint:0.1.0
skills:
- valory/abstract_abci:0.1.0
- valory/abstract_round_abci:0.1.0
- valory/oracle_abci:0.1.0
- valory/oracle_deployment_abci:0.1.0
- valory/price_estimation_abci:0.1.0
- valory/registration_abci:0.1.0
- valory/reset_pause_abci:0.1.0
- valory/safe_deployment_abci:0.1.0
- valory/transaction_settlement_abci:0.1.0
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - console
      propagate: false
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
skill_exception_policy: just_log
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/oracle_abci:0.1.0
---
public_id: valory/ledger:0.1.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://staging.chain.autonolas.tech
      chain_id: 31337
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: staging.acn.autonolas.tech:9005
    public_key: 0250827315351f6f4d3777b77d4bfd67280156240313bf221750b36404344bb35d
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2022-01-01'
  not_before: '2021-01-01'
  public_key: 0250827315351f6f4d3777b77d4bfd67280156240313bf221750b36404344bb35d
  save_path: .certs/acn_cosmos_9005.txt
