name: counter
author: valory
version: 0.1.0
description: A set of agents incrementing a counter
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeidoybzzjch4djhhafqm4e4jcrpaqmlthntcnonlsjtowwpykbc5xi
fingerprint_ignore_patterns: []
number_of_agents: 1
agent: valory/counter:0.1.0:bafybeihkyyfz6ekcto67ikcmhejpjovm7274teglxqt5cvxwhl5jpkqoaa
deployment: {}
dependencies: {}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_COUNTER_RPC:str:http://host.docker.internal:8545}
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559
