name: counter
author: valory
version: 0.1.0
description: A set of agents incrementing a counter
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeidoybzzjch4djhhafqm4e4jcrpaqmlthntcnonlsjtowwpykbc5xi
fingerprint_ignore_patterns: []
number_of_agents: 1
agent: valory/counter:0.1.0:bafybeify4av6iw474edl4q26743rcymeopfvmcfvhjawnrqsbti2e3udh4
network: hardhat
